// =====================================================================
// DATOS DE PRUEBA: PRODUCTOS
// ---------------------------------------------------------------------
// Simulan la tabla "productos" + "variantes" de la base de datos.
// Cada producto incluye variantes (talla, color) con su propio stock
// y precio, tal como lo pide el modelo de datos del proyecto.
// =====================================================================

import type { Producto, Variante } from "@/lib/tipos";

// Helper local para construir variantes de forma compacta.
// Genera un id único dentro del producto a partir de talla + color.
function v(talla: string, color: string, stock: number, precio: number): Variante {
  return { id: `${talla.toLowerCase()}-${color.toLowerCase()}`, talla, color, stock, precio };
}

export const productos: Producto[] = [
  // ============================ BOTAS ============================
  {
    id: "p-bota-rodeo",
    slug: "bota-vaquera-rodeo",
    nombre: "Bota Vaquera Clásica Rodeo",
    descripcion:
      "Bota de cuero genuino con puntera redondeada y tacón vaquero. Costura decorativa de doble hilo para máxima durabilidad.",
    categoriaId: "cat-botas",
    precio: 1250,
    precioAnterior: 1500,
    moneda: "GTQ",
    imagenes: [],
    variantes: [
      v("40", "Negro", 8, 1250),
      v("41", "Negro", 6, 1250),
      v("42", "Café", 10, 1250),
      v("43", "Café", 4, 1250),
    ],
    destacado: true,
    enOferta: true,
    calificacion: 4.8,
    numResenas: 124,
    stockTotal: 28,
    umbralStock: 8,
    disponible: true,
  },
  {
    id: "p-bota-llanero",
    slug: "bota-trabajo-llanero",
    nombre: "Bota de Trabajo Llanero",
    descripcion: "Bota resistente para el trabajo de campo, suela antiderrapante y refuerzo en la puntera.",
    categoriaId: "cat-botas",
    precio: 899,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("40", "Negro", 12, 899), v("42", "Negro", 9, 899), v("44", "Café", 5, 899)],
    destacado: false,
    enOferta: false,
    calificacion: 4.5,
    numResenas: 67,
    stockTotal: 26,
    umbralStock: 6,
    disponible: true,
  },
  {
    id: "p-bota-avestruz",
    slug: "bota-avestruz-premium",
    nombre: "Bota de Avestruz Premium",
    descripcion: "Bota de lujo en piel de avestruz, terminado artesanal y plantilla acolchada de confort.",
    categoriaId: "cat-botas",
    precio: 2400,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("41", "Cognac", 3, 2400), v("42", "Cognac", 2, 2400)],
    destacado: true,
    enOferta: false,
    calificacion: 4.9,
    numResenas: 41,
    stockTotal: 5,
    umbralStock: 5,
    disponible: true,
  },
  {
    id: "p-botin-potro",
    slug: "botin-potro",
    nombre: "Botín de Cuero Potro",
    descripcion: "Botín de caña corta, ideal para el uso diario, con cierre lateral y suela flexible.",
    categoriaId: "cat-botas",
    precio: 650,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("39", "Negro", 7, 650), v("40", "Negro", 5, 650)],
    destacado: false,
    enOferta: false,
    calificacion: 4.3,
    numResenas: 28,
    stockTotal: 12,
    umbralStock: 4,
    disponible: true,
  },

  // ============================ SOMBREROS ============================
  {
    id: "p-sombrero-ranchero",
    slug: "sombrero-fieltro-ranchero",
    nombre: "Sombrero de Fieltro Ranchero",
    descripcion: "Sombrero de fieltro de lana con ala moldeada y cinta de cuero trenzada.",
    categoriaId: "cat-sombreros",
    precio: 450,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("58", "Negro", 14, 450), v("60", "Marrón", 10, 450)],
    destacado: true,
    enOferta: false,
    calificacion: 4.6,
    numResenas: 89,
    stockTotal: 24,
    umbralStock: 6,
    disponible: true,
  },
  {
    id: "p-sombrero-palma",
    slug: "sombrero-palma-costeno",
    nombre: "Sombrero de Palma Costeño",
    descripcion: "Sombrero tejido a mano en palma, fresco y ligero para el clima cálido.",
    categoriaId: "cat-sombreros",
    precio: 320,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("57", "Beige", 20, 320), v("59", "Beige", 15, 320)],
    destacado: false,
    enOferta: false,
    calificacion: 4.4,
    numResenas: 53,
    stockTotal: 35,
    umbralStock: 10,
    disponible: true,
  },
  {
    id: "p-sombrero-jalisco",
    slug: "sombrero-charro-jalisco",
    nombre: "Sombrero Charro Jalisco",
    descripcion: "Sombrero charro de gala con bordados en hilo dorado y galón de adorno.",
    categoriaId: "cat-sombreros",
    precio: 780,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("60", "Negro", 6, 780)],
    destacado: true,
    enOferta: false,
    calificacion: 4.8,
    numResenas: 32,
    stockTotal: 6,
    umbralStock: 6,
    disponible: true,
  },
  {
    id: "p-sombrero-desierto",
    slug: "sombrero-ala-ancha-desierto",
    nombre: "Sombrero de Ala Ancha Desierto",
    descripcion: "Ala extra ancha para protección solar, con barboquejo ajustable.",
    categoriaId: "cat-sombreros",
    precio: 540,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("58", "Marrón", 9, 540), v("59", "Negro", 7, 540)],
    destacado: false,
    enOferta: false,
    calificacion: 4.5,
    numResenas: 21,
    stockTotal: 16,
    umbralStock: 5,
    disponible: true,
  },

  // ============================ CINTURONES ============================
  {
    id: "p-cinturon-toro",
    slug: "cinturon-cuero-toro",
    nombre: "Cinturón de Cuero Toro",
    descripcion: "Cinturón de cuero grueso con hebilla sencilla de acero inoxidable.",
    categoriaId: "cat-cinturones",
    precio: 280,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("34", "Negro", 18, 280), v("36", "Café", 16, 280), v("38", "Café", 11, 280)],
    destacado: false,
    enOferta: false,
    calificacion: 4.5,
    numResenas: 74,
    stockTotal: 45,
    umbralStock: 12,
    disponible: true,
  },
  {
    id: "p-cinturon-aguila",
    slug: "cinturon-grabado-aguila",
    nombre: "Cinturón Grabado Águila",
    descripcion: "Cinturón con grabado de águila y hebilla intercambiable de diseño exclusivo.",
    categoriaId: "cat-cinturones",
    precio: 390,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("36", "Negro", 8, 390), v("38", "Negro", 6, 390)],
    destacado: true,
    enOferta: false,
    calificacion: 4.7,
    numResenas: 45,
    stockTotal: 14,
    umbralStock: 5,
    disponible: true,
  },
  {
    id: "p-cinturon-rodeo",
    slug: "cinturon-vaquero-rodeo",
    nombre: "Cinturón Vaquero Rodeo",
    descripcion: "Cinturón de uso rudo con costura reforzada y hebilla desmontable.",
    categoriaId: "cat-cinturones",
    precio: 220,
    precioAnterior: 300,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("34", "Café", 22, 220), v("36", "Café", 19, 220)],
    destacado: false,
    enOferta: true,
    calificacion: 4.3,
    numResenas: 60,
    stockTotal: 41,
    umbralStock: 12,
    disponible: true,
  },
  {
    id: "p-cinturon-campeon",
    slug: "cinturon-doble-hebilla-campeon",
    nombre: "Cinturón Doble Hebilla Campeón",
    descripcion: "Cinturón de campeonato con doble hebilla dorada y detalles grabados.",
    categoriaId: "cat-cinturones",
    precio: 350,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("36", "Café", 7, 350)],
    destacado: false,
    enOferta: false,
    calificacion: 4.4,
    numResenas: 18,
    stockTotal: 7,
    umbralStock: 4,
    disponible: true,
  },

  // ============================ CAMISAS ============================
  {
    id: "p-camisa-ranchero",
    slug: "camisa-cuadros-ranchero",
    nombre: "Camisa Vaquera de Cuadros",
    descripcion: "Camisa de franela a cuadros, corte recto y botones de presión.",
    categoriaId: "cat-camisas",
    precio: 320,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("M", "Rojo", 15, 320), v("L", "Rojo", 12, 320), v("XL", "Azul", 9, 320)],
    destacado: false,
    enOferta: false,
    calificacion: 4.5,
    numResenas: 96,
    stockTotal: 36,
    umbralStock: 10,
    disponible: true,
  },
  {
    id: "p-camisa-western",
    slug: "camisa-denim-western",
    nombre: "Camisa Denim Western",
    descripcion: "Camisa de mezclilla con canesú western y broches metálicos.",
    categoriaId: "cat-camisas",
    precio: 280,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("M", "Azul", 18, 280), v("L", "Azul", 14, 280)],
    destacado: true,
    enOferta: false,
    calificacion: 4.6,
    numResenas: 71,
    stockTotal: 32,
    umbralStock: 8,
    disponible: true,
  },
  {
    id: "p-camisa-charra",
    slug: "camisa-blanca-charra",
    nombre: "Camisa Blanca de Botones",
    descripcion: "Camisa blanca clásica de vestir, con botonadura nacarada y puños rígidos.",
    categoriaId: "cat-camisas",
    precio: 260,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("S", "Blanco", 10, 260), v("M", "Blanco", 13, 260)],
    destacado: false,
    enOferta: false,
    calificacion: 4.4,
    numResenas: 39,
    stockTotal: 23,
    umbralStock: 8,
    disponible: true,
  },
  {
    id: "p-camisa-pionero",
    slug: "camisa-manga-larga-pionero",
    nombre: "Camisa de Manga Larga Pionero",
    descripcion: "Camisa de algodón de manga larga con detalles en el pecho y botones de madera.",
    categoriaId: "cat-camisas",
    precio: 340,
    precioAnterior: 420,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("M", "Verde", 8, 340), v("L", "Verde", 6, 340)],
    destacado: false,
    enOferta: true,
    calificacion: 4.3,
    numResenas: 27,
    stockTotal: 14,
    umbralStock: 5,
    disponible: true,
  },

  // ============================ PANTALONES ============================
  {
    id: "p-jeans-rodeo",
    slug: "jeans-vaquero-rodeo",
    nombre: "Jeans Vaquero Rodeo",
    descripcion: "Jeans de mezclilla resistente de corte recto, ideal para montar y trabajar.",
    categoriaId: "cat-pantalones",
    precio: 420,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("32", "Azul", 14, 420), v("34", "Azul", 12, 420), v("36", "Azul", 8, 420)],
    destacado: true,
    enOferta: false,
    calificacion: 4.7,
    numResenas: 118,
    stockTotal: 34,
    umbralStock: 8,
    disponible: true,
  },
  {
    id: "p-pantalon-trabajo",
    slug: "pantalon-mezclilla-trabajo",
    nombre: "Pantalón de Mezclilla Trabajo",
    descripcion: "Pantalón de trabajo con refuerzo en rodillas y bolsillos amplios.",
    categoriaId: "cat-pantalones",
    precio: 380,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("34", "Azul", 16, 380), v("36", "Azul", 13, 380)],
    destacado: false,
    enOferta: false,
    calificacion: 4.5,
    numResenas: 64,
    stockTotal: 29,
    umbralStock: 8,
    disponible: true,
  },
  {
    id: "p-jeans-moderno",
    slug: "jeans-skinny-moderno",
    nombre: "Jeans Skinny Moderno",
    descripcion: "Corte ajustado moderno con elasticidad para mayor comodidad.",
    categoriaId: "cat-pantalones",
    precio: 350,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("30", "Negro", 9, 350), v("32", "Negro", 11, 350)],
    destacado: false,
    enOferta: false,
    calificacion: 4.2,
    numResenas: 42,
    stockTotal: 20,
    umbralStock: 6,
    disponible: true,
  },
  {
    id: "p-pantalon-montura",
    slug: "pantalon-cuero-montura",
    nombre: "Pantalón de Cuero Montura",
    descripcion: "Pantalón de cuero para monta, resistente al desgaste y con protección lateral.",
    categoriaId: "cat-pantalones",
    precio: 900,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("34", "Negro", 4, 900), v("36", "Negro", 3, 900)],
    destacado: true,
    enOferta: false,
    calificacion: 4.8,
    numResenas: 22,
    stockTotal: 7,
    umbralStock: 4,
    disponible: true,
  },

  // ============================ ACCESORIOS ============================
  {
    id: "p-panuelo-norteno",
    slug: "panuelo-seda-norteno",
    nombre: "Pañuelo de Seda Norteño",
    descripcion: "Pañuelo cuadrado de seda con estampado norteño, para cuello o bolsillo.",
    categoriaId: "cat-accesorios",
    precio: 90,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("Única", "Rojo", 30, 90), v("Única", "Negro", 25, 90)],
    destacado: false,
    enOferta: false,
    calificacion: 4.3,
    numResenas: 55,
    stockTotal: 55,
    umbralStock: 15,
    disponible: true,
  },
  {
    id: "p-hebilla-estrella",
    slug: "hebilla-acero-estrella",
    nombre: "Hebilla de Acero Estrella",
    descripcion: "Hebilla fundida en acero con acabado plateado y motivo de estrella.",
    categoriaId: "cat-accesorios",
    precio: 150,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("Única", "Plata", 40, 150)],
    destacado: true,
    enOferta: false,
    calificacion: 4.6,
    numResenas: 83,
    stockTotal: 40,
    umbralStock: 12,
    disponible: true,
  },
  {
    id: "p-espuelas-clasicas",
    slug: "espuelas-clasicas",
    nombre: "Espuelas Clásicas",
    descripcion: "Espuelas de acero inoxidable con rodaja y correas de cuero.",
    categoriaId: "cat-accesorios",
    precio: 280,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("Única", "Acero", 12, 280)],
    destacado: false,
    enOferta: false,
    calificacion: 4.5,
    numResenas: 31,
    stockTotal: 12,
    umbralStock: 5,
    disponible: true,
  },
  {
    id: "p-guantes-doma",
    slug: "guantes-cuero-doma",
    nombre: "Guantes de Cuero Doma",
    descripcion: "Guantes de cuero suave con refuerzo en la palma para doma y trabajo.",
    categoriaId: "cat-accesorios",
    precio: 240,
    precioAnterior: 290,
    moneda: "GTQ",
    imagenes: [],
    variantes: [v("M", "Café", 10, 240), v("L", "Café", 8, 240)],
    destacado: false,
    enOferta: true,
    calificacion: 4.4,
    numResenas: 26,
    stockTotal: 18,
    umbralStock: 6,
    disponible: true,
  },
];
